/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {

  DocsSidebar: [
    {
      type: 'doc',
      id: 'intro', 
      label: 'Überblick', 
    },
    {
      type: 'doc',
      id: 'Einführung Datenbanken', 
      label: 'Einführung Datenbanken', 
    },
    {
      type: 'category',
      label: 'Editor',
      items: [{
        type: 'autogenerated',
        dirName: '02_Editor',
      }],
    },
    {
      type: 'category',
      label: 'Autorenwerkzeug',
      items: [{
        type: 'autogenerated',
        dirName: '03_Autorenwerkzeug',
      }],
    },
    {
      type: 'category',
      label: 'SQLite Befehle',
      items: [{
        type: 'autogenerated',
        dirName: '04_SQLite Befehle',
      }],
    },
  

    
  ],
};